---
# tasks file for k8s-worker
- name: Configurando Firewall
  command: firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
  register: firewallconf
- debug: msg="{{ firewallconf.stdout }}"
- name: Refrescar servicio firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: True
- name: Añadiendo Workers a Master
  command: kubeadm join {{ master }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ discovery-token }} 
  register: firewallconf