---
# tasks file for k8s-worker
- name: Añadiendo Workers a Master
  command: kubeadm join {{ master }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ discoverytoken }} 
  register: addworker
- debug: msg="{{ addworker.stdout }}"