---
- name: installing kubernetes cluster
  hosts: k8snodes
  become: true
  vars:
    user: "terra"
    nfs: "nfs-jfurio.westeurope.cloudapp.azure.com"
    master: "master-jfurio.westeurope.cloudapp.azure.com"
    worker0: "worker0-jfurio.westeurope.cloudapp.azure.com"
    worker1: "worker1-jfurio.westeurope.cloudapp.azure.com"
  roles:
    - kubernetes