---
- name: Instalando Prerrequisitos
  hosts: k8snodes
  become: true
  vars:
    nfs: "104.40.150.226"
    master: "40.91.213.158"
    worker0: "52.232.96.152"
    worker1: "51.145.136.34"
  roles:
    - ./roles/kubernetes