---
- name: Instalando servicio NFS
  hosts: nfs
  become: true
  vars:
    master: "master-jfurio.westeurope.cloudapp.azure.com"
    worker0: "worker0-jfurio.westeurope.cloudapp.azure.com"
    worker1: "worker1-jfurio.westeurope.cloudapp.azure.com"
  roles:
    - nfs
    
    
