---
- name: Install NFS Service
  hosts: nfs
  become: true

  tasks:
    - name: Actualización de SO
      dnf:
        name: "*"
        state: latest
    - name: Configuración de sincronización horaria
      command: timedatectl set-timezone Europe/Madrid
    - name: Instalación de Chrony
      dnf:
        name: chrony
        state: latest
    - name: Desactivación de SELinux
      command: sed -i s/=enforcing/=disabled/g /etc/selinux/config
    - name: Instalación de paquetes
      dnf:
        name: '{{ item }}'
        state: latest
      with_items:
        - nfs-utils
        - nfs4-acl-tools
        - wget
        - net-tools
    - name: Habilitar servicio NFS
      systemd:
        name: nfs-server
        enabled: yes
        masked: no
    - name: Iniciar servicio NFS
      systemd:
        name: nfs-server
        state: started
        enabled: True