---
- name: Crear directorio kubectl
  file:
    path: /root/.kube
    state: directory
- name: Copia de fichero de kubectl
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
- name: Modificando ficheros fichero kubectl
  file:
    path: $HOME/.kube/config 
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
- name: Comprobando nodos
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{ getnodes.stdout }}"
