---
- name: Añadiendo repositorio Docker
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
- name: Instalando Docker-ce
  command: dnf install docker-ce --nobest -y
- name: Instalación de paquete containerd.io
  dnf:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm
    state: present
- name: Habilitar servicio Docker
  systemd:
    name: docker
    enabled: yes
    masked: no
- name: Iniciar servicio Docker
  systemd:
    name: docker
    state: started
    enabled: True
- name: Copiando fichero kubernetes.repo
  copy:
    src: ../files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
- name: Instalando paquetes de Kubernetes
  command: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
- name: Habilitar kubelet
  systemd:
    name: kubelet
    enabled: yes
    masked: no
- name: Iniciar kubelet
  systemd:
    name: kubelet
    state: started
    enabled: True